* Notes on M4 Fill Architecture and Extensions

** Flow of Filling Demand

- Default supply is in Deployable-Buckets under :default
- ~compute-supply~ maps _category_ to additional _supply_ computed beyond 
  default deployable assumptions (indicated by presence in a deployable bucket).
- ~find-feasible-supply~ maps one or more _categories of supply_ {cat units} through
  a map of _src_ preferences (via _src-map_, which denotes substituts), constrained by a
  _category_ (optional), to collect a seq of units weighted by _substitution path length_.
- This _ordered supply_ (ordered by substitution weight, implicitly filtered by
  substitutible units), is then filtered by _where_ and sorted by _order-by_.
- We control _computed-supply_, _deployable supply_, _preference_, _feasibility_, by 
  ~demand->rule~ and substition (_src-map_)

There is a reference in fillarch.graphml that depicts the functional dependencies
for this.

** Documentation RFIs
- restricted categories needs to be better documented and explained.
- ~derive-category~ needs to be better documented and explained.

